title: Binary
revisionInfo: '<a href="https://github.com/kolmodin/binary/commit/{{rev}}">GitHub</a>'
limitRecent: 20
start: 4853c7b467409468ac9029558c8ed3caa4a4be6c

benchmarks:
  - match: "throughput/*"
    smallerIsBetter: False
    unit: MB/s
    group: "Throughput measurements"
