title: Gipeda itself
diffLink:
revisionInfo: '<a href="https://github.com/nomeata/gipeda/commit/{{rev}}">View Diff</a>'
limitRecent: 20
start: 65b3eede043ff5d4718724d220a82bbc8adc3280
interestingTags: "*"

benchmarks:
  - match: "*"
    smallerIsBetter: False
    threshold: 1
    type: integral
    group: (ungrouped)
  - match: "loc/*"
    unit: lines of code
    group: Lines of Code
  - match: comment-rate
    unit: percentags
    group: Code quality
